site_name: KarChunT Wiki
site_url: https://karchunt.github.io/karchunt-wiki/
repo_url: https://github.com/KarChunT/karchunt-wiki
repo_name: KarChunT/karchunt-wiki
edit_uri: edit/main/docs/
use_directory_urls: true
theme:
  name: material
  direction: ltr
  logo: assets/logo.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    # - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.share
    - search.suggest
    - search.highlight
    # - navigation.sections
    # - navigation.prune
    # - toc.integrate
    # - header.autohide
  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/KarChunT
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/karchuntan
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/karchunt
  consent:
    title: "Cookies ðŸª"
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
  analytics:
    provider: google
    property: ""
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # alternate:
#     - name: English
#       link: /en/
#       lang: en
#     - name: ä¸­æ–‡
#       link: /zh/
#       lang: zh
copyright: >-
  Copyright &copy; 2025 KarChunT. All rights reserved. â€“
  <a href="#__consent">Change cookie settings</a>
plugins:
  # - offline
  - privacy
  - search
  - glightbox
  # - git-authors
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        font_family: JetBrains Mono
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      exclude:
        - index.md
        - docs/index.md
      enabled: !ENV [CI, false]
  - git-committers:
      enabled: !ENV [CI, false]
      repository: KarChunT/karchunt-wiki
      branch: main
      exclude:
        - index.md
        - docs/index.md
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/mermaid.mjs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - Home: index.md
  - Docs:
    - docs/index.md
    - SSH:
        - Introduction:
          - SSH Overview: docs/ssh/ssh-overview.md
          - SSH Installation: docs/ssh/ssh-installation.md
        - SSH Keys:
          - Play with SSH Keys: docs/ssh/play-with-ssh-keys.md
        - Host & Server:
          - Remote Server Configuration: docs/ssh/remote-server-configuration.md
          - Host Configuration: docs/ssh/host-configuration.md
          - Server Configuration: docs/ssh/server-configuration.md
        - SSH Tunnels:
          - Local Tunneling: docs/ssh/local-tunneling.md
          - Remote Tunneling: docs/ssh/remote-tunneling.md
    - Git:
        - Introduction:
          - What is Git?: docs/git/what-is-git.md
          - Git Installation: docs/git/git-installation.md
          - Git in Depth: docs/git/git-in-depth.md
        - Getting Started with Git:
          - Setup Repository: docs/git/setup-repository.md
          - Save Changes: docs/git/save-changes.md
          - Branches: docs/git/branches.md
          - Remote Repositories: docs/git/remote-repositories.md
          - Rebasing: docs/git/rebasing.md
          - Reset and Revert: docs/git/reset-and-revert.md
          - Stashing: docs/git/stashing.md
        - Advanced:
          - Reflog: docs/git/reflog.md
    - 12 Factor App: docs/12-factor-app.md
    - Python OOP:
        - Introduction:
          - Concepts of Object-Oriented Programming (OOP): docs/python-oop/concepts.md
          - Cohesion & Coupling: docs/python-oop/cohesion-and-coupling.md
        - Core Topics:
          - Class & Object: docs/python-oop/class-and-object.md
          - Encapsulation: docs/python-oop/encapsulation.md
          - Inheritance: docs/python-oop/inheritance.md
          - Polymorphism: docs/python-oop/polymorphism.md
          - Abstraction: docs/python-oop/abstraction.md
        - Class Diagram:
          - UML Class Diagram: docs/python-oop/uml-class-diagram.md
    - Docker:
      - Introduction:
        - What is Docker?: docs/docker/what-is-docker.md
        - Docker Architecture: docs/docker/docker-architecture.md
        - Docker Installation: docs/docker/docker-installation.md
        - Daemon Configuration: docs/docker/daemon-configuration.md
      - Core Topics:
        - Container: docs/docker/container.md
        - Image: docs/docker/image.md
        - Volume: docs/docker/volume.md
        - Network: docs/docker/network.md
        - Resource Limits: docs/docker/resource-limits.md
        - Docker Compose: docs/docker/docker-compose.md
      - Additional:
        - Useful Commands: docs/docker/useful-commands.md
        - Best Practices for Creating Docker Image: docs/docker/best-practices-for-creating-docker-image.md
        - Future Enhancements: docs/docker/future.md
